### ISSUE TITLE
Update EPG/Station Cache At Certain Times of Day

### ISSUE THREAD

**Issue by Croq360** [wouterdebie/locast2dvr#15]
With the current station cache, you can turn it on or off and have stations get updated every X number of seconds.  I'd like to suggest an option that would allow you to specify certain times of day to make this happen.  That'd make the updates more predictable, and you could specify in Emby/Plex a time of day to update their copy.

Perhaps something like this (note that cache-timeout and cache-updatetime would be independent, one or the other):

--cache-stations              Cache station data  [default: True]
    --cache-timeout INTEGER       Time to cache station data in seconds [default: 3600]
    --cache-updatetime time1,time2,...       Time(s) of day to update cache (uses 24h time) - (example: 0030,0230,0415,2230)

**Comment by wouterdebie** [comment]
Interesting idea and I might implement this at some point. The way I did it the way it works right now is because it's really easy to use a timer that just executes every x seconds (in this case `cache-timeout` seconds). Adding update time would be a somewhat bigger effort though. I actually chose the timeout of 1h, because the grabbing all the data from locast.org isn't that big of a deal. The time it takes isn't that much and neither is the volume of data. And since it's done in a background thread, the performance of locast2dvr isn't impacted either. Lastly, it seems that locast updates their EPG every hour as well, looking 8 days ahead.
The actual update of the EPG in Emby/Plex however is somewhat of a bigger deal, since it will also download images, etc. In any way, what are you really trying to optimize for?

**Comment by Croq360** [comment]
The main thing I was going for was to not be hitting the servers as often, and with the current implementation, it's possible that you could have Plex/Emby updating their guide and while doing that, your EPG update happens.  Had something weird occur this morning where the guide was all messed up when I checked it when I got up.  Monitoring that to see what might have caused that to mess up.  Maybe it was taking too long and gave up.

Regarding downloading of images, I would have thought that Emby/Plex would cache those in some way and not need to re-download them every time they update the guide.

**Comment by wouterdebie** [comment]
I'm not too concerned with hitting their API too often. Once an hour a few requests shouldn't be that impactful.

The other thing you're talking about is the chance of a race condition. I encountered this a few weeks ago, where I was running with all zipcodes override (23 DVRs) and the response to Emby's update took too long (> 30 seconds or so), which caused Emby to time out and wipe out the complete EPG. 
Initially I would check the age of the EPG data at every request and if it had expired, I would download it from locast (and taking a hit every hour). I've revised this and instead, updating of the EPG happens on a separate thread every `cache_timeout` seconds and is decoupled from the actual return of the stations. In other words, Emby/Plex requesting the EPG from locast2dvr doesn't lead to locast2dvr calling to locast.org. There is one piece in the code where I replace the stations that locast2dvr holds, but that's guarded by a lock.
