### ISSUE TITLE
Difficulty Closing Locast2Dvr.exe

### ISSUE THREAD

**Issue by Croq360** [wouterdebie/locast2dvr#21]
When I run the program in Windows in a command prompt, hitting Ctrl-C doesn't seem to kill the program.  Usually I can go into task manager and end task, but sometimes, it doesn't show there.  In order to kill it reliably, I have to use Process Explorer and kill either Locast2Dvr.exe (I can also kill the underlying Python process, but either seems to work).

**Comment by wouterdebie** [comment]
I noticed this as well trying it in windows a while ago. I don't really know how to solve it though. I tried catching some interrupts, but that didn't work. Leaving this open for now and maybe there's someone with some ideas.

**Comment by Croq360** [comment]
This code sample works if I save it as "program.py" and run the command "python program.py":

import signal
import sys
import time

def signal_handler(sig, frame):
    print('You pressed Ctrl+C!')
    sys.exit(0)
signal.signal(signal.SIGINT, signal_handler)
print('Press Ctrl+C')
time.sleep(9999)

**Comment by wouterdebie** [comment]
I'm pretty sure I tried this, but since locast2dvr spawns a bunch of threads, it might not work. I might want to redo the way threads are created anyway, since there is currently not a nice way to clean them up. 

Anyway, could you try adding this to main.py or cli.py and see if it works? (I don't have a windows environment set up currently).

**Comment by Croq360** [comment]
Ok, will add it to my list for tonight... :)

**Comment by Croq360** [comment]
I haven't been able to get this tested out yet.  Busy with our remap testing.  Will get back to this once that's done.
