### ISSUE TITLE
Running locast2dvr in the background?

### ISSUE THREAD

**Issue by eqpaisley** [wouterdebie/locast2dvr#24]
I see there's a startup service. It will take me a while to disect that and make it work in the mean time, is it possible to run it from the command line and have it run in the background.  Right now, closing my SSH window closes the program.

**Comment by wouterdebie** [comment]
The way of running locast2dvr in the background is described in the readme,
at least for distributions with systemd.
Another way is to run locast2dvr in tmux or screen or run it with `nohup
locast2dvr .... &`.
I would suggest reading up on linux fundamentals though, since your
question isn't really related to locast2dvr.
