### ISSUE TITLE
Add Docker stuff

### ISSUE THREAD

**Issue by wouterdebie** [wouterdebie/locast2dvr#4]
I'd probably be nice to add a Dockerfile in order to run locast2dvr inside a Docker container.

**Comment by Tuckie** [comment]
Yes please!

**Comment by shinycard255** [comment]
any update on this? 

locast2plex is not working for me and was told of this earlier today!

**Comment by eiddor** [comment]
@wouterdebie I was thinking about taking a crack at this using some `Dockerfile` examples from other related projects (this would be my first Dockerfile beyond just messing about locally, so it may take a while).

However, I saw [over here](https://github.com/wouterdebie/locast2dvr/issues/26#issuecomment-788490345) that you're rewriting things in Rust.  Should I wait and then attempt to do it then?

**Comment by wouterdebie** [comment]
@eiddor I'm pretty close wrapping up the Rust implementation, but I currently have other things I need to focus on, so it might take a few weeks before this will be ready to go. Having something in the locast2dvr repo wouldn't be a waste, since we could always reuse this for locast2tuner.

**Comment by eiddor** [comment]
@wouterdebie Ok, I'm in the same boat as you time-wise, but this may not be too heavy of a lift - It would at least a good basic challenge for me!

I will probably have a couple of project questions, though - For example:

The one thing I'm seeing in the locast2plex project `Dockerfile` is a hook into the project code itself that the fHDHR `Dockerfile` does not bother with (I know they're different projects, but this particular concept should be similar).

The locast2plex `Dockerfile` creates a file post-install that is read by the code:

**Dockerfile:**
```
RUN touch /app/is_container
```

**[user_config.py](https://github.com/tgorgdotcom/locast2plex/blob/main/lib/user_config.py)**

```
        if os.path.exists(pathlib.Path(script_dir).joinpath('is_container')):
            self.data["main"]["bind_ip"] = "0.0.0.0"
            self.data["main"]["bind_port"] = "6077"
        else:
            self.data["main"]["bind_ip"] = self.data["main"]["plex_accessible_ip"]
            self.data["main"]["bind_port"] = self.data["main"]["plex_accessible_port"]
```

I am the _furthest_ thing from a coder (I'm a network person) and have only very basic Python reading skills, but here's my take:

If we detect that we're running in a container, `bind_ip` is set to 0.0.0.0 (all IPs), otherwise we set `bind_ip` to `plex_accessible_ip`, which is 0.0.0.0 by default unless overridden in `config.ini`

I can't really find the equivalent function in locast2dvr, so I'm not sure if it is something I need to account for.

The fHDHR [`Dockerfile`](https://github.com/fHDHR/fHDHR/blob/main/Dockerfile) is more straightforward and basically just installs/runs the package:

```
FROM python:3.8-slim
  
RUN apt-get -qq update && \
    apt-get -qq -y install ffmpeg gcc && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/*

COPY ./ /app/
WORKDIR /app
RUN pip3 install -r requirements.txt

ENTRYPOINT ["python3", "/app/main.py", "--config", "/app/config/config.ini"]
```

Step 1 for me is to get locast2dvr working for me without Docker - I just discovered locast this morning!

**Comment by eiddor** [comment]
> I guess the equivalent would be --bind-address in cli.py, but I'm unsure if we need to account for it.

Thinking about this, we probably do want to force the ip and port if we're running in a container, but I can probably just do that from the `ENTRYPOINT` (assuming we can take CLI options and read a config file at the same time):

`ENTRYPOINT ["localst2dvr", "--config", "/app/config.ini", "--bind-address", "0.0.0.0", "--port", "6077"]

Another question I have - Do we have any data that we need to persist other than `config.ini`?

**Comment by wouterdebie** [comment]
@eiddor I think you're right. Just start locast2dvr with `--bind-address 0.0.0.0`. Tbh, locast2plex does a lot of strange things :)

After copying the source tree in to the container, I'd install locast2dvr with `pip install .`. This installs all the runtime dependencies and the app itself.

**Comment by eiddor** [comment]
Yeah, I'm only using locast2plex/fHDHR to figure out the basic structure relative to the `Dockerfile` since they're a good simple ones to start with.

Here's what I've got so far - using fHDHR's as a template.  

```
FROM python:3.8-slim

RUN apt-get -qq update && \
    apt-get -qq -y install ffmpeg gcc && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/*

COPY ./ /app/
WORKDIR /app
RUN pip3 install localst2dvr

ENTRYPOINT ["localst2dvr", "--config", "/app/config.ini"]
```

I haven't tested this at all yet, as I'm still trying to think some things through, so I'm sure it won't work.  I plan on messing with it more this weekend.

It's definitely going to be very inelegant at first until I can figure out some kind of wrapper (maybe based on yours) that will allow for options on the Docker CLI or in `docker-compose.yaml`.  I'll probably have to find someone with a bit more scripting expertise for help with that.  

For now the user will have to create `config.ini` somewhere and add it as a volume in the Docker config.  Baby steps and a definite learning experience for me.

**Comment by eiddor** [comment]
Ok, this is working well so far:

`Dockerfile`

```
FROM python:3.8-slim

RUN apt-get -qq update && \
    apt-get -qq -y install ffmpeg gcc && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/*

#COPY ./ /app/
WORKDIR /app
RUN pip3 install locast2dvr

ENTRYPOINT ["locast2dvr", "--config", "/app/config/config.ini"]
```

Test results (image names may be different in the final push):

```
roddie@plex:~/dev$ docker run -p 6077:6077 -v /home/roddie/dev/config:/app/config locast2dvr
INFO - Main: locast2dvr 0.8.1 running on CPython 3.8.8, Linux-5.4.0-66-generic-x86_64-with-glibc2.2.5 starting
INFO - LocastService: Logging in with me@here.net
ERROR - Main: User didn't donate
```
It will also work with `docker-compose`:

`docker-compose.yaml`

```
version: '3'
services:
  locast2dvr:
    image: locast2dvr
    container_name: locast2dvr
    volumes:
      - /home/roddie/dev/config:/app/config
    ports:
      - 6077:6077
    restart: unless-stopped
```

Results:

```
roddie@plex:~/dev$ docker-compose up
Creating network "dev_default" with the default driver
Creating locast2dvr ... done
Attaching to locast2dvr
locast2dvr    | INFO - Main: locast2dvr 0.8.1 running on CPython 3.8.8, Linux-5.4.0-66-generic-x86_64-with-glibc2.2.5 starting
locast2dvr    | INFO - LocastService: Logging in with me@here.net
locast2dvr    | ERROR - Main: User didn't donate
locast2dvr    | INFO - Main: locast2dvr 0.8.1 running on CPython 3.8.8, Linux-5.4.0-66-generic-x86_64-with-glibc2.2.5 starting
locast2dvr    | INFO - LocastService: Logging in with me@here.net
locast2dvr    | ERROR - Main: User didn't donate
locast2dvr exited with code 1
```

The user will have to create a `config.ini` and put it in a directory.  They will then have to specify that directory as a volume mapping on the `docker run` CLI or in `docker-compose.yaml`.

TODO

short term (ie. before I open a PR or push to Docker hub)
- donate to locast so I can test fully
- figure out how to document this clearly (something similar to [this](https://fhdhr.github.io/fHDHR_Docs/installation_docker/) I guess)

longer term:
- allow for more flexibility for the user including the ability to specify `locast2dvr` options on the Docker CLI or in `docker-compose.yaml` instead of requiring `config.ini`
- wrapper inside of the container for above

**Comment by eiddor** [comment]
Well that was pretty painless - Running under the same `docker-compose.yaml` file as my Plex, connected it using the external host IP port 6077.

![image](https://user-images.githubusercontent.com/7586731/111044019-a56fb400-840b-11eb-8747-43ae8ceaea05.png)


![image](https://user-images.githubusercontent.com/7586731/111044010-98eb5b80-840b-11eb-86d4-74161b4ef306.png)

**Comment by wouterdebie** [comment]
@eiddor Amazing! Would you mind creating a pull request with the Dockerfile?

**Comment by eiddor** [comment]
@wouterdebie I will once I'm positive that it's working - 

When I try to tune to a channel in Plex, I'm getting "Could not tune channel.  Please check your tuner or antenna."

![image](https://user-images.githubusercontent.com/7586731/111055149-88050f00-8438-11eb-855a-8aeb9087f5df.png)

Emby with M3U just gives me a spinning circle (Emby is on a different machine):

![image](https://user-images.githubusercontent.com/7586731/111055256-bf27f000-8439-11eb-803a-f54ece30b6fd.png)

I need to run locast2dvr outside of Docker and test, so I'm going to spin up a fresh Ubuntu VM to do that with.  I just want to make sure Docker isn't the cause of my problem.

**Comment by eiddor** [comment]
I knew that was too easy :-) 

It works outside of Docker, so I need to figure out what the difference is. I may need your help with this part, @wouterdebie , since beyond turning `-v` on, I don't really know what I'm looking for or how things are supposed to work.

I'll look for a difference in any logs and try a few other things to see what I can figure out.

Here's the log output from when I click "play" to watch a channel - Everything until this point appears to work fine (adding the stream, and even the XMLTV guide).

**Non-working (172.21.0.2 is the Plex container):**

```
2021-03-14 04:31:19,438 - INFO - HTTPInterface: 0.0.0.0:6077 172.21.0.2 - - "GET /discover.json HTTP/1.0" 200 286 "-" "PlexMediaServer/1.22.0.4163-d8c4875dd"
2021-03-14 04:31:19,439 - INFO - HTTPInterface: 0.0.0.0:6077 172.21.0.2 - - "GET /lineup.json HTTP/1.0" 200 3684 "-" "PlexMediaServer/1.22.0.4163-d8c4875dd"
2021-03-14 04:31:19,442 - INFO - HTTPInterface: 0.0.0.0:6077 172.21.0.2 - - "GET /lineup_status.json HTTP/1.0" 200 89 "-" "PlexMediaServer/1.22.0.4163-d8c4875dd"
2021-03-14 04:31:19,464 - INFO - HTTPInterface: 0.0.0.0:6077 172.21.0.2 - - "GET /discover.json HTTP/1.0" 200 286 "-" "PlexMediaServer/1.22.0.4163-d8c4875dd"
2021-03-14 04:31:19,467 - INFO - HTTPInterface: 0.0.0.0:6077 172.21.0.2 - - "GET /lineup_status.json HTTP/1.0" 200 89 "-" "PlexMediaServer/1.22.0.4163-d8c4875dd"
```

**Working: (10.1.1.11 is the host I'm running locast2dvr on, 10.1.1.203 is my Plex server)**

```
2021-03-13 21:55:08 - INFO - HTTPInterface: 10.1.1.11:6077 10.1.1.203 - - "GET 
/discover.json HTTP/1.0" 200 292 "-" "PlexMediaServer/1.22.0.4163-d8c4875dd"     
2021-03-13 21:55:08 - INFO - HTTPInterface: 10.1.1.11:6077 10.1.1.203 - - "GET 
/lineup.json HTTP/1.0" 200 3813 "-" "PlexMediaServer/1.22.0.4163-d8c4875dd"      
2021-03-13 21:55:08 - INFO - HTTPInterface: 10.1.1.11:6077 10.1.1.203 - - "GET 
/lineup_status.json HTTP/1.0" 200 89 "-" "PlexMediaServer/1.22.0.4163-d8c4875dd" 
2021-03-13 21:55:08 - INFO - HTTPInterface: Watching channel 233 on 10.1.1.11:60
77 for Dallas using ffmpeg                                                       
2021-03-13 21:55:11 - INFO - HTTPInterface: 10.1.1.11:6077 10.1.1.203 - - "GET 
/discover.json HTTP/1.0" 200 292 "-" "PlexMediaServer/1.22.0.4163-d8c4875dd"     
2021-03-13 21:55:11 - INFO - HTTPInterface: 10.1.1.11:6077 10.1.1.203 - - "GET 
/lineup_status.json HTTP/1.0" 200 89 "-" "PlexMediaServer/1.22.0.4163-d8c4875dd" 
2021-03-13 21:55:13 - INFO - HTTPInterface: 10.1.1.11:6077 10.1.1.203 - - "GET 
/watch/233 HTTP/1.1" 200 - "-" "Lavf/58.27.104"
```

**Comment by eiddor** [comment]
Ok, so I narrowed it down - locast2dvr doesn't like being bound to `0.0.0.0`.  

Oddly enough, my test results were inconsistent between ffmpeg mode and `ds` mode inside of Docker, but it may be the same root cause.

Connection | ffmpeg (PMS) Results | ds (Emby) Results
----- | ----- | -----
Docker Host mode bound to Host IP | working | working
Docker Bridge mode bound to container IP | working | not working
Docker any mode bound to `0.0.0.0` | not working | not working
Native bound to Host IP | working | working
Native bound to `0.0.0.0` | not working | not working

So, there are two workarounds for PMS (ffmpeg) and one for Emby (ds), but IMHO they put too of a burden on the user to either:

a) run in Host mode, which is just not a great practice

b) know their container IPs and hope that they never change

What's really strange is that in every test scenario above, I can add locast2dvr as a Live TV source, get channel info, EPG, etc.  It's only when trying to actually play a channel that things break.

On the bright side, you can test this _without_ Docker by binding to 0.0.0.0: `locast2dvr --config config.ini --bind-address 0.0.0.0 -v --logfile blah.log`

Thoughts @wouterdebie ?

**Comment by RandomNinjaAtk** [comment]
I'm seeing similar results, I started putting a docker together for this after being unable to get locast2plex to function. This is functioning in host mode as said. Otherwise I'm seeing similar results.

**Comment by eiddor** [comment]
@RandomNinjaAtk Looking at [this](https://github.com/RandomNinjaAtk/unraid-templates/issues/17#issuecomment-801176266) - 

You're able to bind to 0.0.0.0 in bridge mode and it works with Emby?  Is that using HD Homerun or M3U Tuner?

**Comment by RandomNinjaAtk** [comment]
@eiddor Correct, it did function with emby normally from my brief test

**Comment by eiddor** [comment]
@RandomNinjaAtk Can you tell me what mode (HD Homerun or M3U Tuner) you were testing with Emby?  I want to test it here to see if I can add some more results to the matrix above.

Also, if Plex and Emby behave differently with the same setup, it may give @wouterdebie a bit more information about where to look.

This brings me back to my original question about whether it's worth the effort since it's going to be rewritten in Rust, anyway.

**Comment by RandomNinjaAtk** [comment]
My tests were all using it as HD Homerun. I haven't had time to mess around with it more though

**Comment by wouterdebie** [comment]
FYI, I just pushed a working Rust version at https://github.com/wouterdebie/locast2tuner. Let me know what you think. I'm considering deprecating this project over the new one, but only after creating proper packages and such.

**Comment by eiddor** [comment]
Awesome, @wouterdebie!  I've never touched Rust before, so I'll try to get it going locally and then work on Dockerizing it as well as maybe adding some notes in the documentation based on what works for me on the Ubuntu host that it will run on.

Hoping I don't hit the same network snags I hit with the Python version (which may have been triggered by ffmpeg in the first place).

**Comment by eiddor** [comment]
Docker discussion and stuff moved to the new project: https://github.com/wouterdebie/locast2tuner/issues/17
