### ISSUE TITLE
SSDP broken

### ISSUE THREAD

**Issue by wouterdebie** [wouterdebie/locast2dvr#8]
SSDP doesn't seem to work. Neither Emby nor PMS seems to be able to find locast2dvr

**Comment by deathbybandaid** [comment]
Going to follow this thread as I'm seeing the same thing with a custom SSDP implementation for [fHDHR](https://github.com/fHDHR/).

Since I have varients of the script for different origin content, and I'm using SSDP, I managed to get the varients to 'cluster' together from the web interface.

Setting my logger to debug shows that it's working, but I've always ended up manually adding the ip:port into plex and emby.

**Comment by wouterdebie** [comment]
I've been experiencing the same thing. I've been looking through Emby code to try and figure out what response they expect, but have been unsuccessful so far. Keep me posted if you happen to find something.

**Comment by deathbybandaid** [comment]
I have a theory that I'm playing with, sending a `ssdp:alive` on a refresh interval

**Comment by deathbybandaid** [comment]
Didn't seem to help, but I'm happy with implementing it anyway.

I also noticed in Emby that you can try to autodetect "M3U Tuners", I already have an implemented M3U system, so if there's an SSDP method to broadcast as that as well, I'd like to implement that as well.

Plex is implementing a "Remote Media Grabber" system as well, which differs from how HDHomerun appears.

**Comment by deathbybandaid** [comment]
I posted in the Emby community looking for answers

https://emby.media/community/index.php?/topic/92566-could-use-some-ssdp-help/

**Comment by wouterdebie** [comment]
I disabled SSDP by default since it seems broken, but can be reenabled with `-s/--ssdp`. Will need some further investigation.
